### PR TITLE
[WIP] Invoice line items sync

### PR DESCRIPTION
**Pull request by JustEdro**

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @JustEdro, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @JustEdro!

Thank you for signing the Singer Contribution License Agreement.

**Comment by JustEdro** [comment]
Hello there, I've created this pull request by invitation from your colleague Brian.
These changes are not really ready to be merged into the master so maybe it worth to create a separate branch for them.

**Comment by dmosorast** [comment]
Hi @JustEdro Thank you for submitting this! There's some really good stuff in here.

I've created a branch called `feature/add_invoice_line_items` to track these changes along with master, and will likely be pulling some of the smaller pieces into my working branch as I go, to help with merging.

Could you update the PR's target to `feature/add_invoice_line_items`?

**Comment by JustEdro** [comment]
Hi @dmosorast 
You are welcome! The branch is changed.

**Comment by dmosorast** [comment]
@JustEdro We're ready to pull this substream into master. Due to some refactoring, we'll merge this to the feature branch and make changes there, translating your methods into the methods we've implemented on master.

Specifically:
- We added substream events updates to `subscription_items`, which should cover `invoice_line_items`
- Some of the iteration got cleaned up a bit, so some variables were moved

**Pull request merged**
