### PR TITLE
Transform error fix: Change an object to a string

### PR DESCRIPTION
**Pull request by luandy64**

### CODE REVIEW

**Comment by cmerrick** [comment]
Do the API docs suggest that either of these response types are valid?

**Comment by luandy64** [comment]
The docs show the `evidence` field comes back as an object. However, searching the changelogs of the API, at some point the field was "a single block of text". [Changelog ](https://stripe.com/docs/upgrades#2014-12-08)

**Comment by cmerrick** [comment]
Great detective work :). LGTM.

**Comment by ilkkapeltola** [comment]
This breaks my load to target-snowflake (pipelinewise flavor).
If you would change the order to object first, then string, it would work.

**Pull request merged**
